# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.9.0

executors:
  my-executor:
    docker:
      - image: cimg/node:17.2.0-browsers

jobs:
  myStuff:
    executor: my-executor
    steps:
      - checkout
      - node/install
          node-version: 14.17.3
          npm-version: 6.14.13
      - run:
          name: Echo Step
          command: |
            echo 'How do I get this second job to run in the environment of the first one?'
            ls -al
            pwd
            node -v
            npm -v           
      - run:
          name: Test My Code
          command: |
           mkdir -p test-results
           npm run test > test-results/testresults.xml
      - store_artifacts:
          path: myArtifacts
          destination: myPrefix
      - store_test_results:
          path: test-results
  complete:
    executor: my-executor
    steps:
      - run:
          name: Dan's Approval
          command: |
            echo 'Approved?'

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2
  hello-world-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - node/test:
          test-results-for: jest
      - myStuff
      - waitForApproval:
          type: approval
          requires: 
              - myStuff
      - complete:
          requires: 
            - waitForApproval